### ISSUE TITLE
Export preliminary round 1 adjudication data

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/ppa-nlp#115]
consult with Laure on where to store on Tigerdata

**Comment by mnaydan** [comment]
@laurejt I exported the round 1 adjudications I have so far and uploaded it to google drive here: [https://drive.google.com/file/d/1UxTl7e1D4XYqQ29pz3gu6TtoUjl96akc/view?usp=drive_link](https://drive.google.com/file/d/1UxTl7e1D4XYqQ29pz3gu6TtoUjl96akc/view?usp=drive_link) Let me know if you'd like me to upload it to TigerData too, I'll put it wherever you think is best.
