### ISSUE TITLE
write core evaluation script for passim

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#126]
- [ ] requires evaluation data (minimal)

**Comment by laurejt** [comment]
The core code for evaluating poetry spans is available in the branch [feautre/eval-spans](https://github.com/Princeton-CDH/ppa-nlp/tree/feature/eval-spans)

The following components still need to be completed:
- Implementing the I/O functionality for evaluating the page-level reference & system spans
- Completing unit tests for the following two methods:
  1. `PageEvaluation._get_span_mappings`
  2. `PageEvaluation._get_span_pairs`
