### ISSUE TITLE
Create PPA page-level OCR quality evaluation

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#23]
- [x] Implement page-level language detection measurement
- [x] Implement dictionary lookup extrinsic measurement
- [x] Generate results & perform basic analysis

**Comment by laurejt** [comment]
Notes on the results & basic analysis are located [here](https://docs.google.com/document/d/1ez-VqQ6z5toieuFJQigAbQucqN3n7IyYqOpyJTD5wA0/edit#heading=h.5z4n9uahwv3c).
