### ISSUE TITLE
Get an image and text aligned dataset for the new test set

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#26]
- [x] Gather HathiTrust images
- [ ] Gather Gale images
- [x] Get updated text for entire PPA collection
- [x] Build test-specific text corpus (filtering to specific page ranges)
- [ ] Change the names of the files

**Comment by laurejt** [comment]
Major road block encountered. I've uncovered major inconsistencies in the ECCO metadata spreadsheets when it comes to the image folder locations. Putting this on pause for now.

Current status: 13/14 Gale-sourced volumes have been uploaded
