### ISSUE TITLE
transfer ECCO data from harddrives to SSD

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/ppa-nlp#36]
- [ ] Determine what's on ECCOI HD
- [ ] Determine what's on ECCOII HD
- [x] Create script for transferring (and reorganizing files)
- [ ] Transfer files to SSD

**Comment by mnaydan** [comment]
We don't need this anymore because all the ECCO-PPA data we need is on Tigerdata; we'll hold on to the hard drives until we confirm, but eventually we may want to give to PUL to deal with.
