### ISSUE TITLE
mark single author/single poems in PPA metadata

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/ppa-nlp#37]

**Comment by mnaydan** [comment]
[https://docs.google.com/spreadsheets/d/158UW0YuD8Kk41ahi8KOkEXCEDABlAbmvFcAd-9b7A_s/edit?usp=sharing](https://docs.google.com/spreadsheets/d/158UW0YuD8Kk41ahi8KOkEXCEDABlAbmvFcAd-9b7A_s/edit?usp=sharing)
