### ISSUE TITLE
As a researcher, I want to be able to get the text corpus for a subset of record IDs so that I can conduct textual analysis within particular groups of texts.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#5]
## acceptance criteria
- [x] filter script successfully filters the corpus and generates a subset corpus that includes all pages for the specified source ids and only pages for those source ids
    - [x]  for simple `idfile` (one source_id per line; non-excerpt sources)
    - [x] for simple `idfile` with leading whitespace
    - [x] for simple `idfile` with trailing whitespace
    - [x] for `idfiles` with sources with 1 or more excerpts
    - [x] for `idfiles` with a mix of existing and non-existing sources
- [x] filter script has reasonable error handling (missing/empty id file, output file already exists)

**Comment by rlskoeser** [comment]
Here's a screen recording of my terminal showing the corpus subset functionality:


https://github.com/Princeton-CDH/ppa-nlp/assets/691231/68057e2c-e324-468f-96e5-7fde847a6549

**Comment by laurejt** [comment]
Should an output file be created if there are no matches?

**Comment by rlskoeser** [comment]
> Should an output file be created if there are no matches?

I guess ideally not, but I don't think there's an easy way to detect this until after consuming the generator. I guess we could check and remove it after if it's zero size.

**Comment by laurejt** [comment]
Testing acceptance complete. The only outstanding issue, is whether the script should produce empty output files when no matches are found (either way seems reasonable).

**Comment by rlskoeser** [comment]
Thanks for testing. Let's leave the empty file behavior as it is for now, we've both put enough time into this feature already. We can always revisit and tweak it later if we find it's causing problems.
