### ISSUE TITLE
debug Prodigy session issue

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#61]

**Comment by rlskoeser** [comment]
@laurejt notes towards configuring verbose logging (`PRODIGY_LOGGING=verbose`):

Here's the line in cdh-ansible where we configure the environment variables for prodigy running in supervisor:

https://github.com/Princeton-CDH/cdh-ansible/blob/main/inventory/group_vars/prodigy/vars.yml#L53 

I suggest we add a new ansible variable for logging level and pass that in to the supervisor config.

**Comment by rlskoeser** [comment]
testing on staging, reloading my session in the browser and I get some alternation (not necessarily every time) between the next page to annotate changes and the total number of annotations saved on my session goes from 34 to 36 (which makes me suspect something is going on between the two servers (whether a session thing or a prodigy hashing issue)

<img width="1318" alt="Screenshot 2024-08-12 at 1 06 10 PM" src="https://github.com/user-attachments/assets/ac53469f-98f1-4821-9c07-803677f8f834">

<img width="1320" alt="Screenshot 2024-08-12 at 1 08 01 PM" src="https://github.com/user-attachments/assets/ae632ad8-b4d8-44ad-8855-2f69c8212a3a">

**Comment by rlskoeser** [comment]
We've updated the config on the PUL load balancer to only use one VM for each staging/production instance, to avoid the possibility of switching between different task queues. This should be resolved now, but I'm not sure how or if we can confirm.
