### ISSUE TITLE
run Google Vision OCR script on initial 300 Gale image subset

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#74]

**Comment by laurejt** [comment]
The approximate cost for digitizing these 14 volumes (~3.9K images) was $5.85

**Comment by mnaydan** [comment]
@laurejt amazing, this is so exciting!! Curious if/how we're handling excerpts/articles: I believe one of the 14 volumes was an article.

**Comment by laurejt** [comment]
Since this currently only operates at the volume level, the entire volume was OCR'd.
