### ISSUE TITLE
load adjudication recipe on local environment

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#75]
Recipe needs to allow for character-level text span annotations, which the original annotators for round 1 couldn't do because they did tokens. 

If possible, we should use Prodigy's built-in review recipe: [https://prodi.gy/docs/recipes#review](https://prodi.gy/docs/recipes#review)

**Comment by laurejt** [comment]
**For testing of the Adjudication recipe:**
- [ ] Displays annotations with session-name prefix (numerical suffix for "duplicate" sessions)
- [ ] Unique colors for annotators
- [ ] Character-based highlighting
- [ ] Progress bar reflects completed annotations 
- [ ] Cannot submit flagged task
- [ ] Cannot submit task with overlapping spans
