### ISSUE TITLE
Extend corppa-filter-corpus so that specific pages can be specified

### ISSUE THREAD

**Issue by laurejt** [Princeton-CDH/ppa-nlp#82]
The existing filter corpus script cannot filter to a specific set of pages, whether they are known via their names (i.e. `id` field) or their work (`work_id`) and digital page (`order`) ids.

@rlskoeser and I have discussed several possible solutions including:
- Use mutlisets so that the `include` option can store multiple values for the same key.
- New option to take an input csv/tsv with header, with each record corresponding to a key-value pair set to filter for.

One additional option could be to instead take a .jsonl file. This would allow additional flexibility that each record could use a different set of fields / keys.

While not specifically tied to this issue. It'd also be nice if this script could take a list of ids instead of a line-separate file. This should be possible using the argparse's `extend` action.

**Comment by mnaydan** [comment]
Simplest version is to take a CSV that has volumeID and digital page ID and use that to populate your filters
