### ISSUE TITLE
Investigate utility of DINOv2 on page images from the test set

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#9]
Test set [here](https://docs.google.com/spreadsheets/d/1xsIk17ii_PuArkupCqY4bexXKX2JMp1_02oqlU9Yn3Q/edit?usp=sharing).

Page images in [this folder on Google Drive](https://drive.google.com/drive/folders/1Dv7XBDC-qAHozPteEM6yuAkQlgIcYNjx?usp=drive_link)

- [ ] comment and close

**Comment by laurejt** [comment]
On visualizing extracted features (i.e. page image embeddings): I tested out two different tools for visualizing image embedding.
1. [PixPlotML](https://github.com/alexhock/pixplotml):
This tool still looks promising, especially for image annotation. However, there was a key limitation. Namely, all images needed to be in a single, flat directory. This is unideal when working with 10K+ images. Adapting the codebase to work with images in multiple (sub)directories may be possible, but it was out of scope for this task.
2. [TensorBoard Embedding Projector](https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin)
A working prototype is available on the [experiment/image-projection](https://github.com/Princeton-CDH/ppa-nlp/tree/experiment/image-projection) branch. One limitation with this particular tool is that several of the projection/dimensionality reduction algorithms downsample the number of features used for faster results (T-SNE: 10K; UMAP: 5K).

**Comment by laurejt** [comment]
Using the image projection prototype, the test set contains a wide variety of visual features and DINOv2 (dinov2-small) appears to capture these salient features (as seen via the projection clustering / nearest neighbors).
