### ISSUE TITLE
data prep for Prodigy annotations round 2

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#90]
- [x] 300 pages
- [x] select pages to include from spreadsheet (150)
- [x] +n number of pages
- [x] add image paths
- [x] convert Gale images (#46)
- [x] document process

**Comment by laurejt** [comment]
Documentation still needs to be completed but the final dataset is on tigerdata at `ppa-prodigy/datasets/poetry-gale300a.jsonl`

**Comment by laurejt** [comment]
The construction is documented [here](https://docs.google.com/document/d/1iP9QlR9Ln2SAb8en7a2oAOjKxftn-Okhqo0BXRMB7HY/edit)
